config/routes.rb
GolBlog::Application.routes.draw do
  

  resources :users
  
  resources :posts do
    resources :comments
  end

  

   root :to => 'posts#index'

   match ':controller(/:action(/:id))(.:format)'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :body, :commenter, :post_id
  validates :body, :length => { :maximum => 250 }
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :dependent => :destroy
  attr_accessible :body, :title, :user_id
  validates :title, :length => { :maximum => 200 }
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  attr_accessible :email, :name, :password, :avatar, :avatar_cache
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(params[:comment])
    @comment.save
    
    redirect_to @post
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    #@comment = @post.comments.find(params[:comment_id])
    @comment.destroy
    
    #redirect_to @post
    respond_to do |format|  
      #format.html { redirect_to(posts_url) } 
      format.html { redirect_to(@post) }
      format.js   { render :layout => false }
      format.json { head :no_content }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    
    #@posts = Post.all
    @posts = Post.find(:all, :order => "created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/OLDdestroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/destroy.js.erb
$('.delete_comment').bind('ajax:success', function() {  
        $(this).closest('div').fadeOut();
});  

app/views/layouts/Copy of application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GolBlog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>Golblog</title>
		  	<%= stylesheet_link_tag    "application", :media => "all" %>
  			<%= javascript_include_tag "application" %>
  			<%= javascript_include_tag :defaults %>
  			<%= csrf_meta_tags %>
  </head>
  <body>
		<div id='pagewrapper'>
			<div id='header'>
				<p>GolBloG - The best blog on the web!</p>
		  </div>
			<div id='navbar'>
				<ul>
					<li><%= link_to 'Home', :root %></li>
					<li><%= link_to 'New Post', {:controller => 'posts', :action => 'new'} %></li>
			    	<li><%= link_to 'User Admin', {:controller => 'users', :action => 'index'} %></li>
			    	<li><%= link_to 'Sign Up', {:controller => 'users', :action => 'new'} %></li>
				</ul>
		  <div>
		</div>
		<div id='content'>
      <%= yield %>
		</div>
		<div id='footer'>
			<p>GolBlog 2013. All rights reserved.</p>
		</div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Welcome to GolBlog!</h1>

<% @posts.each do |post| %>
	<h2><%= link_to post.title, post %></h2>
	<p>
		<%= time_ago_in_words post.created_at %> ago
	</p>
	<p>
		<%= truncate post.body%>
	</p>
<% end %>

<p>
	<%= link_to "New post", new_post_path %>
</p>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html copy.erb
<h1><%= @post.title %></h1>

<%= @post.body %>

<h2>Comments</h2>

<% @post.comments.each do |comment| %>
	<p><b><%= comment.commenter %> wrote: </b><%= comment.body %></p>
	<p><%= time_ago_in_words comment.created_at %> ago</p>
	<!-- DELETE COMMENT WITH AJAX -->
	<p><%= link_to "Delete comment", [@post, comment], method: :delete, data: {confirm: "Are you sure?"} %></p>
<% end %>

<%= form_for [@post, @post.comments.build] do |f| %>
	<p><%= f.label "Name" %><br />
		<%= f.text_field :commenter %></p>
	<p><%= f.label :body %><br />
		<%= f.text_area :body, :size => '40x10'%></p>
	<p><%= f.submit "Post comment" %></p>
<% end %>

<p>
<%= link_to "Back", posts_path %> 
|
<%= link_to "Edit", edit_post_path(@post)%>
|
<%= link_to "Delete", @post, method: :delete, data: {confirm: "Are you sure?"} %>
</p>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<%= @post.body %>

<h2>Comments</h2>

<% @post.comments.each do |comment| %>
	<p><b><%= comment.commenter %> wrote: </b><%= comment.body %></p>
	<p><%= time_ago_in_words comment.created_at %> ago</p>
	<p><%= link_to "Delete comment", [@post, comment], method: :delete, data: {confirm: "Are you sure?"} %></p>
<% end %>

<%= form_for [@post, @post.comments.build] do |f| %>
	<p><%= f.label "Name" %><br />
		<%= f.text_field :commenter %></p>
	<p><%= f.label :body %><br />
		<%= f.text_area :body, :size => '40x10'%></p>
	<p><%= f.submit "Post comment" %></p>
<% end %>

<p>
<%= link_to "Back", posts_path %> 
|
<%= link_to "Edit", edit_post_path(@post)%>
|
<%= link_to "Delete", @post, method: :delete, data: {confirm: "Are you sure?"} %>
</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="fiel">
    <label>My Avatar</label>
    <%= f.file_field :avatar %>
    <%= f.hidden_field :avatar_cache %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/login.html.erb
<h1>Login page</h1>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%=# link_to 'Back', users_path 
%>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
	<b>Avatar:</b>
	<%= image_tag(@user.avatar, :size => "40x40") %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>